version: "3.7"

# For connection urls to the following instances, see
# https://github.com/prisma/prisma/blob/main/TESTING.md#environment-variables
services:
 # Replica Set (required for Prisma Client)
 mongo:
  build: ./mongodb
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: prisma
   MONGO_REPLICA_HOST: 127.0.0.1
   MONGO_REPLICA_PORT: 27017
  ports:
   - "27017:27017"
