[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1.24", features = ["sync", "rt-multi-thread", "macros"] }
rust-bert = "0.20.0"
tch = "0.10.1"